Repository gcivil-nyu-org/wed-fall24-team1, pull requests merged in 2024-10, with the labels that each got.

#22 Adding to dynamodb and showing as a table
  Database/db-fetch.py
  Database/db-foods.py
  Database/db-mental.py
  Database/db-restrooms.py
  Database/db-shelters.py
  Database/db-table.py
  Database/foods.csv
  Database/mental.csv
  Database/restrooms.csv
  Database/shelters.csv
  public_service_finder/public_service_finder/settings.py
  public_service_finder/public_service_finder/urls.py
  public_service_finder/users/views.py
  public_service_finder/viewdb/__init__.py
  public_service_finder/viewdb/admin.py
  public_service_finder/viewdb/apps.py
  public_service_finder/viewdb/migrations/__init__.py
  public_service_finder/viewdb/models.py
  public_service_finder/viewdb/templates/dynamodb_table.html
  public_service_finder/viewdb/tests.py
  public_service_finder/viewdb/urls.py
  public_service_finder/viewdb/views.py
  requirements.txt
Labels: User Story

#24 Showing services on map
  public_service_finder/public_service_finder/settings.py
  public_service_finder/viewdb/templates/dynamodb_table.html
  public_service_finder/viewdb/views.py
  requirements.txt
Labels: User Story

#51 Provide location to view services near me #12
  src/db.sqlite3
  src/home/templates/partials/_header.html
  src/static/apps/home/js/map.js
Labels: user story

#50 Adding submit review and view functionality #14
  db-prep/db-ratings.py
  db-prep/db-reviews.py
  src/db.sqlite3
  src/home/repositories.py
  src/home/templates/home.html
  src/home/templates/partials/_public_service_list.html
  src/home/templates/partials/_table.html
  src/home/urls.py
  src/home/views.py
  src/public_service_finder/settings.py
  src/static/apps/home/js/map.js
Labels: enhancement

#65 # 19 Implement detailed descriptions for detailed view
  src/home/repositories.py
  src/home/templates/partials/_table.html
  src/home/views.py
  src/static/apps/home/js/map.js
  src/static/css/styles.css
Labels: enhancement

#69 #58 Update ReadME.md
  README.md
Labels: documentation

#85 #79 Bug Fix: Mental/Shelter Category not working
  src/db.sqlite3
  src/home/views.py
Labels: bug

#95 #84 revamped service provider dashboard and create form
  src/public_service_finder/settings.py
  src/services/templates/service_form.html
  src/services/templates/service_list.html
  src/static/css/sp_dashboard.css
  src/static/js/service_form.js
  src/static/js/service_list.js
Labels: enhancement

#97 UI test cases #45
  src/.ebextensions/django.config
  src/accounts/tests.py
  src/public_service_finder/settings.py
Labels: enhancement
