Repository gcivil-nyu-org/wed-fall24-team1, pull requests merged in 2024-11, with the labels that each got.

#114 #108 Implement sort by distance/rating & additional QOL changes
  src/home/templates/partials/_header.html
  src/home/templates/partials/_public_service_list.html
  src/static/apps/home/js/map.js
Labels: enhancement

#117 Adding and removing bookmarks, displaying reviews on user screen and login bug fix
  .flake8
  db-prep/create_bookmarks_table.py
  src/accounts/forms.py
  src/accounts/templates/profile_base.html
  src/accounts/views.py
  src/home/repositories.py
  src/home/templates/home.html
  src/home/templates/partials/_table.html
  src/home/urls.py
  src/home/views.py
  src/public_service_finder/settings.py
  src/services/tests.py
  src/static/css/styles.css
Labels: enhancement

#122 Change logo
  src/static/images/logo-psf.png
Labels: enhancement

#121 As a Service Provider, I want to respond to reviews to address feedback or provide additional information.#101
  src/forum/views.py
  src/home/repositories.py
  src/home/templates/partials/_table.html
  src/home/views.py
  src/public_service_finder/settings.py
  src/public_service_finder/views.py
  src/services/forms.py
  src/services/models.py
  src/services/repositories.py
  src/services/templates/respond_to_review.html
  src/services/templates/review_list.html
  src/services/templates/service_form.html
  src/services/tests.py
  src/services/urls.py
  src/services/views.py
  src/static/js/service_list.js
Labels: user story

#145 Fix review submission bugging out with "decimal.Inexact" error #120
  src/home/repositories.py
  src/home/views.py
Labels: bug

#143 remove any console.logs from our JS #142
  src/home/templates/partials/_table.html
  src/static/apps/home/js/map.js
  src/static/js/service_list.js
Labels: bug

#147 Dashboard
  .travis.yml
  src/home/repositories.py
  src/public_service_finder/templates/base.html
  src/public_service_finder/templates/partials/_navbar.html
  src/services/templates/dashboard.html
  src/services/tests.py
  src/services/urls.py
  src/services/views.py
Labels: enhancement

#149 #137 Implement Bookmark Modal
  src/accounts/templates/profile_base.html
  src/accounts/views.py
  src/static/js/profile.js
Labels: enhancement

#150 As a service provider, I want to be able to mark my service as deactivated/unavailable in case of any downtime #134
  src/home/templates/partials/_table.html
  src/home/views.py
  src/services/forms.py
  src/services/models.py
  src/services/templates/service_form.html
  src/services/templates/service_list.html
  src/services/tests.py
  src/services/views.py
  src/static/js/service_list.js
Labels: user story

#151 #105 notifications for service seekers and providers
  src/.gitignore
  src/forum/admin.py
  src/forum/context_processors.py
  src/forum/migrations/0002_notification.py
  src/forum/migrations/0003_notification_notification_type_and_more.py
  src/forum/models.py
  src/forum/urls.py
  src/forum/views.py
  src/home/templates/home.html
  src/home/tests.py
  src/home/views.py
  src/public_service_finder/settings.py
  src/public_service_finder/templates/partials/_navbar.html
  src/public_service_finder/utils/enums/service_status.py
  src/services/views.py
  src/static/css/styles.css
  src/static/js/nav.js
Labels: user story

#155 UI changes dashboard and UT cases (#127, #140)
  .gitignore
  db-prep/db-fetch-1.py
  src/.gitignore
  src/forum/tests.py
  src/home/tests.py
  src/requirements.txt
  src/services/templates/dashboard.html
  src/services/templates/service_list.html
  src/services/tests.py
  src/services/views.py
  src/static/images/placeholder_service.jpeg
Labels: enhancement

#159 #158 service dashboard search
  src/services/templates/service_list.html
  src/services/tests.py
  src/static/js/service_list.js
Labels: bug

#163 #154 first and last name during rgistration
  src/accounts/forms.py
  src/accounts/migrations/0008_alter_customuser_first_name_and_more.py
  src/accounts/models.py
  src/accounts/templates/register.html
  src/accounts/tests.py
  src/accounts/views.py
Labels: bug

#165 #164 disallow edit username and email for providers
  src/accounts/forms.py
Labels: bug

#170 (#169) Placeholder fix
  src/accounts/forms.py
Labels: bug

#174 Fix Approval Status #173
  src/services/views.py
Labels: bug

#189 #188 client side validation for post and comment edits
  src/forum/templates/create_post.html
  src/static/js/forum_create.js
  src/static/js/forum_edit.js
Labels: testing party

#191 #184 timezone must be based on the client
  src/forum/templates/category_detail.html
  src/forum/templates/post_detail.html
  src/home/templates/partials/_table.html
  src/static/js/forum_common.js
  src/static/js/profile.js
Labels: testing party

#190 #185 clear review fields after submission
  src/home/templates/partials/_table.html
Labels: testing party

#193 #184 timezone follow ups for the profile and service lists
  src/accounts/templates/profile_base.html
  src/forum/templates/category_detail.html
  src/forum/templates/post_detail.html
  src/services/templates/service_list.html
  src/static/js/common.js
  src/static/js/profile.js
  src/static/js/service_list.js
Labels: bug

#195 (#141) Adding navbar and footer to login pages
  src/accounts/templates/register.html
  src/accounts/templates/service_provider_login.html
  src/accounts/templates/user_login.html
  src/services/tests.py
Labels: enhancement

#196 (#167) Search bar fix
  db-prep/services-normalized.py
  src/home/repositories.py
Labels: bug

#198 (#194) Fixing reviews line break and XSS protection
  src/home/templates/partials/_table.html
  src/services/tests.py
Labels: bug

#197 #179 & #180 Fix blank description item addition logic
  src/services/forms.py
  src/static/js/service_form.js
Labels: bug

#206 #139: B3-edit-delete
  src/home/repositories.py
  src/home/templates/partials/_table.html
  src/home/urls.py
  src/home/views.py
  src/services/templates/service_form.html
Labels: user story

#208 #200 logged out users see different navbar options, more cosmetic cha…
  .travis.yml
  src/accounts/templates/register.html
  src/accounts/templates/service_provider_login.html
  src/accounts/templates/user_login.html
  src/public_service_finder/templates/partials/_navbar.html
Labels: enhancement, testing party

#221 #213 403 page for unauthorized views
  src/public_service_finder/templates/403.html
  src/public_service_finder/views.py
Labels: enhancement

#222 #207 forum posts on profile
  src/accounts/templates/profile_base.html
  src/accounts/views.py
  src/static/js/profile.js
Labels: enhancement

#218 (#215) Password reset
  src/accounts/templates/password_reset.html
  src/accounts/templates/password_reset_complete.html
  src/accounts/templates/password_reset_confirm.html
  src/accounts/templates/password_reset_done.html
  src/accounts/templates/password_reset_email.html
  src/accounts/templates/password_reset_subject.txt
  src/accounts/templates/service_provider_login.html
  src/accounts/templates/user_login.html
  src/accounts/urls.py
  src/public_service_finder/settings.py
Labels: bug

#223 #106 providers can make announcements about their service
  src/accounts/templates/profile_base.html
  src/accounts/views.py
  src/home/repositories.py
  src/home/templates/partials/_public_service_list.html
  src/home/templates/partials/_table.html
  src/home/views.py
  src/services/forms.py
  src/services/models.py
  src/services/repositories.py
  src/services/templates/service_form.html
  src/services/templates/service_list.html
  src/services/tests.py
  src/services/views.py
  src/static/js/profile.js
  src/static/js/service_list.js
Labels: user story

#227 #226 profile updates, cosmetic changes
  src/accounts/templates/profile_base.html
  src/home/templates/partials/_table.html
  src/static/js/profile.js
Labels: enhancement

#229 #228 onnect password reset pages to the rest of the app
  src/accounts/templates/password_reset.html
  src/accounts/templates/password_reset_complete.html
  src/accounts/templates/password_reset_confirm.html
  src/accounts/templates/password_reset_done.html
  src/accounts/templates/password_reset_email.html
  src/accounts/templates/password_reset_subject.txt
  src/public_service_finder/settings.py
  src/public_service_finder/templates/partials/_breadcrumbs.html
  src/public_service_finder/templates/partials/_navbar.html
Labels: bug

#230 (#231) UI test cases
  src/home/tests.py
  src/home/urls.py
Labels: enhancement

#219 Dark UI chnages
  src/accounts/forms.py
  src/accounts/templates/lockout.html
  src/accounts/templates/profile_base.html
  src/accounts/templates/register.html
  src/accounts/templates/service_provider_login.html
  src/accounts/templates/user_login.html
  src/accounts/views.py
  src/forum/forms.py
  src/forum/templates/category_detail.html
  src/forum/templates/category_list.html
  src/forum/templates/create_post.html
  src/forum/templates/partials/_pagination.html
  src/forum/templates/post_detail.html
  src/home/templates/home.html
  src/home/templates/partials/_header.html
  src/home/templates/partials/_public_service_list.html
  src/home/templates/partials/_table.html
  src/public_service_finder/templates/admin_only.html
  src/public_service_finder/templates/base.html
  src/public_service_finder/templates/partials/_breadcrumbs.html
  src/public_service_finder/templates/partials/_footer.html
  src/public_service_finder/templates/partials/_navbar.html
  src/public_service_finder/templates/partials/_pagination.html
  src/services/forms.py
  src/services/templates/dashboard.html
  src/services/templates/respond_to_review.html
  src/services/templates/review_list.html
  src/services/templates/service_form.html
  src/services/templates/service_list.html
  src/static/apps/home/js/map.js
  src/static/css/styles.css
  src/static/js/nav.js
  src/static/js/profile.js
  src/static/js/service_list.js
Labels: enhancement
