Repository gcivil-nyu-org/wed-fall24-team1, pull requests merged in 2024-12, with the labels that each got.

#237 Profile picture
  .gitignore
  src/accounts/admin.py
  src/accounts/forms.py
  src/accounts/migrations/0009_customuser_profile_image_url.py
  src/accounts/models.py
  src/accounts/templates/profile_base.html
  src/accounts/templates/register.html
  src/accounts/views.py
  src/public_service_finder/settings.py
  src/public_service_finder/templates/base.html
  src/public_service_finder/templates/partials/_navbar.html
  src/requirements.txt
Labels: enhancement

#220 #178 Sorting by distance/rating only done per page rather than all results
  src/home/templates/partials/_header.html
  src/home/templates/partials/_public_service_list.html
  src/home/views.py
  src/public_service_finder/templates/partials/_navbar.html
  src/static/apps/home/js/map.js
  src/static/js/nav.js
Labels: bug

#240 #216 More dark UI
  src/accounts/forms.py
  src/accounts/templates/password_reset.html
  src/accounts/templates/password_reset_complete.html
  src/accounts/templates/password_reset_confirm.html
  src/accounts/templates/password_reset_done.html
  src/accounts/templates/password_reset_email.html
  src/accounts/templates/register.html
  src/accounts/templates/service_provider_login.html
  src/accounts/templates/user_login.html
  src/accounts/urls.py
  src/home/templates/partials/_header.html
  src/home/templates/partials/_table.html
  src/public_service_finder/templates/partials/_navbar.html
  src/static/apps/home/js/map.js
  src/static/js/table.js
Labels: enhancement

#243 (#244) Service image
  src/accounts/templates/profile_base.html
  src/accounts/views.py
  src/home/templates/partials/_table.html
  src/home/views.py
  src/services/forms.py
  src/services/models.py
  src/services/templates/service_form.html
  src/services/templates/service_list.html
  src/services/views.py
  src/static/js/table.js
Labels: enhancement

#242 #235 service providers can flag reviews
  src/moderation/templates/_flag_modal.html
  src/moderation/tests.py
  src/services/templates/service_list.html
  src/static/js/service_list.js
Labels: user story

#249 #246: image size nginx bug resolved
  src/.platform/nginx/conf.d/client_max_body_size.conf
Labels: bug

#251 #247 only approved services in user bookmarks
  src/home/repositories.py
Labels: bug

#255 License
  LICENSE.txt
Labels: documentation

#257 Documentation
  README.md
Labels: documentation
